#!/bin/bash

echo killing process `ps uax | grep -v grep | grep record_video.py | tr -s " " | cut -d " " -f 2`

# this sends a SIGINT (equal to Ctrl-C) to record_video.py
kill -2 `ps uax | grep -v grep | grep record_video.py | tr -s " " | cut -d " " -f 2`

